#cloud-config
package_update: true
package_upgrade: true

apt:
  sources:
    # from: https://stackoverflow.com/a/62706447
    docker.list:
      source: deb [arch=amd64] https://download.docker.com/linux/ubuntu $RELEASE stable
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

packages:
  # Docker
  - docker-ce
  - docker-ce-cli

  # For SMB mount to Azure Files
  - cifs-utils
  - smbclient

runcmd:
  - mkdir -p /var/lib/cloud/scripts/per-boot
  - mkdir -p /etc/systemd/journald.conf.d/

  # Install caprover core
  # MAIN_NODE_IP_ADDRESS is used ONLY in initial setup. Set it to loopback so we
  # will not need to bust a firewall hole for port 3000 to the outside internet.
  # (This works as long as `caprover serversetup` will run on the same server.)
  - docker run -p 80:80 -p 443:443 -p 3000:3000 -e MAIN_NODE_IP_ADDRESS=127.0.0.1 -e ACCEPTED_TERMS=true -v /captain:/captain -v /var/run/docker.sock:/var/run/docker.sock caprover/caprover

  # Install caprover-cli (will be used for setup), via pnpm (smaller than npm)
  - wget -qO- https://get.pnpm.io/install.sh | sh -
  - PNPM_HOME=/root/.local/share/pnpm PATH="$PNPM_HOME:$PATH" pnpm setup
  - pnpm install -g caprover

write_files:
  - path: /var/lib/cloud/scripts/per-boot/mount-datalake.sh
    # Have the datalake network storage mounted locally at each boot.
    # This `mount-datalake.sh` script is run at each boot (including
    # the very first one, i.e. after instance creation).
    permissions: "0755"
    content: |
      #!/bin/bash
      MOUNT_PATH=/mnt/persistent-storage
      mkdir -p "$MOUNT_PATH"
      mount -t cifs //', parameters('storageAccountName'), '.file.core.windows.net/', parameters('storageAccountFolder'), ' "$MOUNT_PATH" -o "vers=3.0,username=', parameters('storageAccountName'), ',password=', listKeys(resourceId('Microsoft.Storage/storageAccounts', parameters('storageAccountName')), '2022-09-01').keys[0].value, ',dir_mode=0777,file_mode=0777,serverino" || true
