#cloud-config
#
# WARNING: The build process that injects this file into an Azure ARM template
# currently does not support the presence of backslashes or single-quote characters in this file.
#
package_update: true
package_upgrade: true

apt:
  sources:
    # from: https://stackoverflow.com/a/62706447
    docker.list:
      source: deb [arch=amd64] https://download.docker.com/linux/ubuntu $RELEASE stable
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

packages:
  # Docker
  - docker-ce
  - docker-ce-cli

  # For Caprover CLI
  - nodejs

  # For SMB mount to Azure Files
  - cifs-utils
  - smbclient

runcmd:
  - systemctl daemon-reload
  - systemctl enable mnt-persistent-storage.mount
  - systemctl start mnt-persistent-storage.mount

  # Install & run caprover core server
  #
  # MAIN_NODE_IP_ADDRESS is used ONLY in initial setup. Set it to loopback so we
  # will not need to bust a firewall hole for port 3000 to the outside internet.
  # (This works as long as `caprover serversetup` will run on the same server.)
  - docker run -p 80:80 -p 443:443 -p 3000:3000 -e MAIN_NODE_IP_ADDRESS=127.0.0.1 -e ACCEPTED_TERMS=true -v /captain:/captain -v /var/run/docker.sock:/var/run/docker.sock caprover/caprover

  # Install caprover-cli (will be used for setup), via pnpm (smaller than npm)
  #
  # With this profile.d script, very user on the box (except runcmd) will put pnpm in their $PATH
  - |
    cat > /etc/profile.d/pnpm.sh <<EOF
    export PNPM_HOME=/opt/pnpm
    export PATH=\\$PNPM_HOME:\\$PATH
    EOF
  # Install pnpm, having sourced the PNPM environment variables
  - . /etc/profile.d/pnpm.sh ; SHELL=bash bash -c "curl -fsSL https://get.pnpm.io/install.sh | sh -"
  # Install caprover CLI, having sourced the PNPM environment variables
  - . /etc/profile.d/pnpm.sh ; pnpm install -g caprover

write_files:
  - path: /etc/cifs-credentials/persistent-storage
    permissions: "0600"
    content: |
      username=', parameters('storageAccountName'), '
      password=', listKeys(resourceId('Microsoft.Storage/storageAccounts', parameters('storageAccountName')), '2022-09-01').keys[0].value, '

  - path: /etc/systemd/system/mnt-persistent\x2dstorage.mount
    permissions: "0644"
    content: |
      [Unit]
      Description=Azure Files CIFS mount for warehouse persistent storage
      After=network-online.target
      Wants=network-online.target

      [Mount]
      What=//', parameters('storageAccountName'), '.file.core.windows.net/', parameters('storageAccountFolder'), '
      Where=/mnt/persistent-storage
      Type=cifs
      Options=vers=3.0,credentials=/etc/cifs-credentials/persistent-storage,dir_mode=0777,file_mode=0777,serverino

      [Install]
      WantedBy=multi-user.target

  - path: /etc/systemd/system/docker.service.d/override.conf
    permissions: "0644"
    content: |
      [Unit]
      After=mnt-persistent\x2dstorage.mount
      Requires=mnt-persistent\x2dstorage.mount

  - path: /etc/systemd/journald.conf.d/diskspace.conf
    permissions: "0644"
    content: |
      [Journal]
      SystemMaxUse=900M
      MaxRetentionSec=30day
