captainVersion: 4

services:
  $$cap_appname:
    image: $$cap_gc_landing_page_docker_image
    restart: unless-stopped
    environment:
      HOST: "0.0.0.0"
      NODE_ENV: "production"
      NUXT_OAUTH_AUTH0_DOMAIN: $$cap_auth0_domain
      NUXT_OAUTH_AUTH0_CLIENT_SECRET: $$cap_auth0_client_secret
      NUXT_OAUTH_AUTH0_CLIENT_ID: $$cap_auth0_client_id
      NUXT_PUBLIC_COMMUNITY_NAME: $$cap_community_name
      NUXT_PUBLIC_SUPERSET_ENABLED: $$cap_superset_enabled
      NUXT_PUBLIC_FILEBROWSER_ENABLED: $$cap_filebrowser_enabled
      NUXT_PUBLIC_WINDMILL_ENABLED: $$cap_windmill_enabled
      NUXT_PUBLIC_EXPLORER_ENABLED: $$cap_explorer_enabled
      NUXT_PUBLIC_BASE_URL: https://$$cap_appname.$$cap_root_domain
      NUXT_PUBLIC_DOMAIN: $$cap_root_domain
      NUXT_PUBLIC_LOGO_URL: $$cap_logo_url
      NUXT_SESSION_PASSWORD: $$cap_session_password

    caproverExtra:
      containerHttpPort: "8080"

caproverOneClickApp:
  variables:
    - id: "$$cap_gc_landing_page_docker_image"
      label: GC Landing Page Docker Image
      defaultValue: "communityfirst/guardianconnector-landing-page:20260216-83"
      validRegex: /^communityfirst\/guardianconnector-landing-page:[a-zA-Z0-9_][a-zA-Z0-9_.-]{0,127}$/
      description: Check out the container registry for valid tags


    - id: "$$cap_community_name"
      label: Community Name (alias)
      description: The alias of the community used for Guardian Connector (e.g. <community_name>.guardianconnector.net)
    - id: "$$cap_root_domain"
      label: Root Domain
      description: The root domain of the community (e.g. guardianconnector.net)
      
    - id: "$$cap_auth0_domain"
      label: Auth0 Domain
      description: Auth0 domain for authentication
    - id: "$$cap_auth0_client_secret"
      label: Auth0 Client Secret
      description: Auth0 client secret for authentication
    - id: "$$cap_auth0_client_id"
      label: Auth0 Client ID
      description: Auth0 client ID for authentication

    - id: "$$cap_session_password"
      label: Session Password
      defaultValue: "$$cap_gen_random_hex(50)"
      description: Password used for session encryption. Auto-generated if not provided.

    - id: "$$cap_logo_url"
      label: Logo URL
      description: URL of the community logo to display on the landing page

    - id: "$$cap_superset_enabled"
      label: Enable Superset
      defaultValue: "true"
      description: Show Superset as an accessible application link on the landing page
    - id: "$$cap_filebrowser_enabled"
      label: Enable Filebrowser
      defaultValue: "true"
      description: Show Filebrowser as an accessible application link on the landing page
    - id: "$$cap_windmill_enabled"
      label: Enable Windmill
      defaultValue: "true"
      description: Show Windmill as an accessible application link on the landing page
    - id: "$$cap_explorer_enabled"
      label: Enable GC Explorer
      defaultValue: "true"
      description: Show GC-Explorer as an accessible application link on the landing page

  instructions:
    start: |-
      A landing page app for Guardian Connector.
    end: |-
      GC Landing Page is deploying and will be available within a minute.
  displayName: Guardian Connector Landing Page
  isOfficial: true # Only if all images used here are official or from a trusted source.
  description: A landing page for Guardian Connector.
  documentation: https://github.com/ConservationMetrics/gc-landing-page
