name: Build & Publish to GitHub Pages

on:
  push:
    branches:
      - build-assets-to-gh-pages
    paths:
      - 'azure/**'
      - 'caprover/one-click-apps/**'
      - '.github/workflows/build-and-deploy.yml'
      - 'build/**'  # if index pages changed

jobs:
  build:
    name: Build static assets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build ARM template
        run: (cd azure && ./build.sh)

      - name: Copy one-click-apps into build folder
        run: |
          mkdir -p build/one-click-apps
          cp -R caprover/one-click-apps/* build/one-click-apps/

      - name: one-click-apps/README Markdown to HTML
        uses: jaywcjlove/markdown-to-html-cli@main
        with:
          source: caprover/one-click-apps/README.md
          output: build/one-click-apps/index.html
          dark-mode: false
          style: build/bamboo.min.css

      - name: Upload ARM artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          # point to the folder containing your generated JSON
          path: build

  deploy:
    name: Publish to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write       # needed to push to gh-pages
      id-token: write    # needed by deploy-pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy artifact to Pages
        id: deployment
        uses: actions/deploy-pages@v4
